webtalk_init -webtalk_dir D:/Locker/PANEPISTIMIO/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/vga_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 17 22:24:33 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9d898762-e55c-4abd-8997-5af6a77949c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6628781638464a1598cf77f5e7426f69" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "370" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3193 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90368101 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "24.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1408673737 -regid "" -xml D:/Locker/PANEPISTIMIO/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/vga_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Locker/PANEPISTIMIO/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/vga_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Locker/PANEPISTIMIO/lab3/lab3.sim/sim_1/behav/xsim/xsim.dir/vga_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
