make clear:
	clear
	clear

make one:
	javac java_threading/ask3_java_one_thread.java

make two:
	javac java_threading/ask3_java_two_threads.java

make four:
	javac java_threading/ask3_java_four_threads.java

make serial:
	javac java_threading/ask3_java_serial.java

make clean:
	rm java_threading/*.class


	
