make one:
	g++ -ltbb -std=c++0x ask3_tbb_one_thread.cpp

make two:
	g++ -ltbb -std=c++0x ask3_tbb_two_threads.cpp

make four:
	g++ -ltbb -std=c++0x ask3_tbb_four_threads.cpp

make serial:
	g++ ask3_tbb_serial.cpp

make clean:
	rm -rf a.out
	
